#spring配置
spring:
  #1.应用配置
  application:
    name: ihrm-salarys #指定服务名
  #3.JPA
  jpa:
    database: MySQL
    show-sql: true
    open-in-view: true
  #2.数据库连接池
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ihrm?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: 330124
    hikari:
      maximum-pool-size: 2
  redis:
    host: 116.62.26.142
    port: 6379
#服务配置
server:
  port: 9009