server:
  port: 9003
spring:
  application:
    name: ihrm-social-securitys #指定服务名
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/ihrm?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT
    username: root
    password: 330124
  jpa:
    database: MySQL
    show-sql: true
    open-in-view: true
  redis:
    host: 116.62.26.142
    port: 6379
dubbo:
  protocol:
    name: dubbo
    port: 12342
    serialization: java
  registry:
    address: zookeeper://127.0.0.1:2181
  application:
    name: ihrm-social-securitys






