#spring配置
spring:
  #1.应用配置
  application:
    name: ihrm-audit #指定服务名
  #2.数据库连接池
  datasource:
    act:
      jdbc-url: jdbc:mysql://localhost:3306/act?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT
      username : root
      password : 330124
      driver-class-name: com.mysql.jdbc.Driver
    ihrm:
      jdbc-url: jdbc:mysql://localhost:3306/ihrm?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT
      username : root
      password : 330124
      driver-class-name: com.mysql.jdbc.Driver
  redis:
    host: 116.62.26.142
    port: 6379
  #3.JPA
  jpa:
    database: MySQL
    show-sql: true
    open-in-view: true
  activiti:
    history-level: full
    db-history-used: true
server:
  port: 10888
